import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { useState } from 'react'
import { NFTCard } from "../components/nftCard"
import { useRouter } from 'next/router';
import Link from 'next/link';



export default function Home() {
    const [NFTs, setNFTs] = useState([]);
    const collection = "0xfF8053A18f44af056DC718e0A5a344A0B8ccC675";
    const router = useRouter();
    const wallet = router.query.id;
    const fetchNFTs = async() => {
        let nfts; 
        console.log("fetching nfts");
        const api_key = "A8A1Oo_UTB9IN5oNHfAc2tAxdR4UVwfM"
        const baseURL = `https://eth-goerli.g.alchemy.com/v2/${api_key}/getNFTs/`;
        var requestOptions = {
            method: 'GET'
          };
         
    
          console.log("fetching nfts for collection owned by address")
          const fetchURL = `${baseURL}?owner=${wallet}&contractAddresses%5B%5D=${collection}`;
          nfts= await fetch(fetchURL, requestOptions).then(data => data.json())
        
        if (nfts) {
          console.log("nfts:", nfts.ownedNfts)
          setNFTs(nfts.ownedNfts)
        }
      }
    
    
      fetchNFTs()




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainSub}>
        <h1 className={styles.titleUp}>
          作者のページ
        </h1>

        <p className={styles.description}>
            作者を気に入ったら連絡を取ることもできます

            <button>
          作者に連絡する
        </button>
        </p>

        <button>
          <Link href = "/works">
          作品一覧に戻る
          </Link>
        </button>

        <div className={styles.grid}>
        {
          //map 関数を使用して NFT の配列を反復処理し、すべての NFT に対して NFTCard を返し、NFT 自体を NFTCard の小道具として渡します。
          NFTs.length && NFTs.map(nft => {




            return (

              <NFTCard nft={nft} key = {nft}>
              </NFTCard>
              
            )
          })
          
        }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
