import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Prompt Wizards' Guild!</a>
        </h1>

        <p className={styles.description}>
          AI絵師のためのポートフォリオサイト
        </p>

        <div className={styles.grid}>

          <a
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
          <Link href = "/NftUploader">
          <h2>AI絵画を作る &rarr;</h2>
            <p>Stable Diffusionを用いてAI絵画を実際に作ることができます。作品はブロックチェーン上に保存されます。</p>

          </Link>
            
          </a>


          <a
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <Link href = "/works">
            <h2>作品を見る &rarr;</h2>
            <p>
              展示されているAI絵画は全てブロックチェーンに保存されています。気になる作者がいれば連絡を取ることができます。
            </p>
            </Link>

          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
