import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'
import { NFTCard } from "./components/nftCard"



export default function Home() {
    const [NFTs, setNFTs] = useState([]);
    const collection = "0xfF8053A18f44af056DC718e0A5a344A0B8ccC675";
    const fetchNFTsForCollection = async () => {
    
        if (collection.length) {
          var requestOptions = {
            method: 'GET'
          };
          const api_key = "A8A1Oo_UTB9IN5oNHfAc2tAxdR4UVwfM"
          const baseURL = `https://eth-goerli.g.alchemy.com/v2/${api_key}/getNFTsForCollection/`;
          const fetchURL = `${baseURL}?contractAddress=${collection}&withMetadata=${"true"}`;
          const nfts = await fetch(fetchURL, requestOptions).then(data => data.json());
          if (nfts) {
            console.log("NFTs in collection:", nfts);
            setNFTs(nfts.nfts)
    
          }
    
        }
      }
      fetchNFTsForCollection()




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.mainSub}>
        <h1 className={styles.titleUp}>
          Welcome to Works
        </h1>

        <p className={styles.description}>
            気になる作品をクリック
        </p>

        <div className={styles.grid}>
        {
          //map 関数を使用して NFT の配列を反復処理し、すべての NFT に対して NFTCard を返し、NFT 自体を NFTCard の小道具として渡します。
          NFTs.length && NFTs.map(nft => {




            return (

              <NFTCard nft={nft} key = {nft}>
              </NFTCard>
              
            )
          })
          
        }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
